$allergies = array(
	array( "menu-item" => 1, "info" => "Hvete, gluten østers. (fritert i olje som kan inneholde spor av peanøtter og soya)." ),
	array( "menu-item" => 2, "info" => "Hvete, gluten østers. (fritert i olje som kan inneholde spor av peanøtter og soya)." ),
	array( "menu-item" => 3, "info" => "Egg og skalldyr. (kan inneholde spor av gluten)." ),
	array( "menu-item" => 4, "info" => "Egg, østers. (kan inneholde spor av gluten)." ),
	array( "menu-item" => 5, "info" => "Østers. (spor av gluten)." ),
	array( "menu-item" => 6, "info" => "Østers. (spor av gluten)." ),
	array( "menu-item" => 7, "info" => "Cashew nøtter, østers, soya. (gluten)." ),
	array( "menu-item" => 8, "info" => "(kan inneholde spor av gluten)." ),
	array( "menu-item" => 9, "info" => "Østers. (spor av gluten)." ),
	array( "menu-item" => 10, "info" => "Østers. (spor av gluten)." ),
	array( "menu-item" => 11, "info" => "Østers. (spor av gluten)." ),
	array( "menu-item" => 12, "info" => "Østers, gluten. (fritert i olje som kan inneholde spor av peanøtter og soya)." ),
	array( "menu-item" => 13, "info" => "Ingen allergener. (kan inneholde spor av gluten og soya)." ),
	array( "menu-item" => 14, "info" => "Ingen allergener. (kan inneholde spor av gluten)." ),
	array( "menu-item" => 15, "info" => "Egg, østers. (spor av gluten)." ),
	array( "menu-item" => 16, "info" => "Skalldyr, spor av gluten." ),
	array( "menu-item" => 17, "info" => "Skalldyr, hvete, gluten. (fritert i olje som kan inneholde spor av peanøtter og soya)." ),
	array( "menu-item" => 18, "info" => "Egg, gluten, østers." ),
	array( "menu-item" => 19, "info" => "Skalldyr, soya." ),
	array( "menu-item" => 20, "info" => "Ingen allergener. (kan inneholde spor av gluten og soya)." ),
	array( "menu-item" => 21, "info" => "Østers, gluten." ),
	array( "menu-item" => 22, "info" => "Skalldyr, soya, fiskesaus." ),
	array( "menu-item" => 23, "info" => "Skalldyr, soya, fiskesaus, egg." ),
	array( "menu-item" => 24, "info" => "Skalldyr, østers, fiskesaus." ),
	array( "menu-item" => 25, "info" => "Gluten, østers, egg." ),
	array( "menu-item" => 26, "info" => "Peanøtter, soya, gluten." ),
	array( "menu-item" => 27, "info" => "Østers, gluten." ),
	array( "menu-item" => 28, "info" => "Østers, gluten." ),
	array( "menu-item" => 29, "info" => "Østers, gluten." ),
	array( "menu-item" => 30, "info" => "Østers, gluten, soya." ),
	array( "menu-item" => 31, "info" => "Skalldyr, fiskesaus." ),
	array( "menu-item" => 32, "info" => "Egg, cashew nøtter." ),
	array( "menu-item" => 33, "info" => "Skalldyr, fiskesaus, cashew nøtter." ),
	array( "menu-item" => 34, "info" => "Gluten, soya, østers, peanøtter i saus." )
);
